# base image you want to use
# make sure to use a CUDA image if running on GPUs
# FROM nvidia/cuda:XX.X-cudnnX-devel-ubuntuXX.XX
FROM nvidia/cuda:11.4.2-devel-ubuntu20.04
# FROM nvcr.io/nvidia/pytorch:21.09-py3
# FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime

# these two lines are mandatory
WORKDIR /gridai/project
COPY ./movenet ./movenet
COPY ./setup.py .
COPY ./requirements.txt .
COPY ./dev-requirements.txt .

# any RUN commands you'd like to run
# use this to install dependencies
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install curl wget git libsndfile-dev python3-pip -y

RUN pip3 install lightning-grid wandb
RUN pip3 install -e .

RUN ln -s /usr/bin/python3 /usr/bin/python

ENV WANDB_ENTITY=nielsbantilan
