compute:

  provider:
    credentials: ${GRID_PROVIDER_CREDENTIALS}
    region: us-east-1
    vendor: aws

  train:
    disk_size: 512
    instance: t2.2xlarge
    cpus: 7
    gpus: 0
    memory: 32G
    # framework: torch

    datastore_name: ${GRID_DATASTORE_NAME}
    datastore_version: ${GRID_DATASTORE_VERSION}
    datastore_mount_dir: ${GRID_DATASTORE_MOUNT_DIR}

    actions:
      on_image_build:
        - apt-get update -y
        - apt-get install wget libsndfile-dev -y
        - pip install lightning-grid

      on_before_training_start:
        - grid login --username ${GRID_USERNAME} --key ${GRID_API_KEY}
        - grid artifacts ${GRID_ARTIFACTS_RUNS_OR_EXPERIMENTS} --download_dir /artifacts || echo 'skip artifacts download'
