compute:

  provider:
    credentials: ${GRID_PROVIDER_CREDENTIALS}
    region: us-east-1
    vendor: aws

  train:
    disk_size: 300
    instance: p3.2xlarge
    cpus: 3
    gpus: 1
    memory: 60G
    framework: torch

    datastore_name: ${GRID_DATASTORE_NAME}
    datastore_version: ${GRID_DATASTORE_VERSION}
    datastore_mount_dir: ${GRID_DATASTORE_MOUNT_DIR}

    dependency_file_info:
      package_manager: pip
      path: ./requirements.txt

    actions:
      on_image_build:
        - apt-get update -y
        - apt-get install wget libsndfile-dev -y
        - pip install lightning-grid
      on_before_training_start:
        - grid login --username ${GRID_USERNAME} --key ${GRID_API_KEY}
        - grid artifacts ${GRID_ARTIFACTS_RUNS_OR_EXPERIMENTS} --download_dir /artifacts || echo 'skip artifacts download'
        - echo "data store contents" && ls /opt/datastore/**/*
